name: "post slack message"
description: post slack message
inputs:
  SLACK_BOT_TOKEN:
    description: token
    required: true
runs:
  using: composite
  steps:
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: "C05F7UGHD9R"
        # For posting a rich message using Block Kit
        payload: |
          {
            "attachments": [
              {
                "text": "イメージがアップされました。",
                "fields": [
                  {
                    "short": True,
                    "value": "svelte-app",
                    "title": "Repository"
                  },
                  {
                    "short": True,
                    "value": "1.0.0",
                    "title": "Tag"
                  },
                  {
                    "short": True,
                    "value": "app",
                    "title": "Service"
                  },
                  {
                    "short": True,
                    "value": "app",
                    "title": "Container"
                  },
                ]
              },
              {
                "callback_id": "confirm",
                "text": "デプロイしますか？",
                "actions": [
                  {
                    "text": "デプロイする",
                    "type": "button",
                    "name": "deploy",
                    "value": "deploy"
                  },
                  {
                    "text": "デプロイしない",
                    "type": "button",
                    "name": "not_deploy",
                    "value": "not_deploy"
                  },
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}
