name: "post slack message"
description: post slack message
inputs:
  SLACK_BOT_TOKEN:
    description: token
    required: true
  ECR_REPOSITORY:
    description: repository
    required: true
  ECR_TAG:
    description: tag
    required: true
runs:
  using: composite
  steps:
    - name: Set env from dynamodb
      shell: bash
      run: |
        set $(aws dynamodb get-item \
        --table-name ecs_map \
        --key '{ "repository": { "S": "${{ inputs.ECR_REPOSITORY }}" } }' \
        --query 'Item.[cluster.S,service.S,repository.S]' \
        --output text)
        echo "CLUSTER=${1}" >> $GITHUB_ENV
        echo "SERVICE=${2}" >> $GITHUB_ENV
      env:
        AWS_DEFAULT_REGION: "ap-northeast-1"

    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: "C05F7UGHD9R"
        payload: |
          {
            "attachments": [
              {
                "text": "イメージがアップされました。",
                "fields": [
                  {
                    "short": true,
                    "value": "${{ inputs.ECR_REPOSITORY }}",
                    "title": "Repository"
                  },
                  {
                    "short": true,
                    "value": "${{ inputs.ECR_TAG }}",
                    "title": "Tag"
                  },
                  {
                    "short": true,
                    "value": "${{ env.SERVICE }}",
                    "title": "Service"
                  },
                  {
                    "short": true,
                    "value": "${{ env.CLUSTER }}",
                    "title": "Container"
                  }
                ]
              },
              {
                "callback_id": "confirm",
                "text": "デプロイしますか？",
                "actions": [
                  {
                    "text": "デプロイする",
                    "type": "button",
                    "name": "deploy",
                    "value": "deploy"
                  },
                  {
                    "text": "デプロイしない",
                    "type": "button",
                    "name": "not_deploy",
                    "value": "not_deploy"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}
