name: deploy to ecs
description: deploy to ecs
inputs:
  ECR_IMAGE:
    description: Ecr image with deploy tag
    required: true
  TASK_NAME:
    description: Ecr image with deploy tag
    required: true
  CONTAINER_NAME:
    description: Ecr image with deploy tag
    required: true
  CLUSTER_NAME:
    description: Ecr image with deploy tag
    required: true
  SERVICE_NAME:
    description: Ecr image with deploy tag
    required: true
runs:
  using: composite
  steps:
    - name: Download task definition
      shell: bash
      run: |
        aws ecs describe-task-definition --task-definition ${{ inputs.TASK_NAME }} --query taskDefinition > task-definition.json

    - name: Render Amazon ECS task definition
      id: render-web-container
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ inputs.CONTAINER_NAME }}
        image: ${{ inputs.ECR_IMAGE }}

    - name: Deploy to Amazon ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.render-web-container.outputs.task-definition }}
        service: ${{ inputs.SERVICE_NAME }}
        cluster: ${{ inputs.CLUSTER_NAME }}
