name: "dispatch-ecs-deploy"
description: "dispatch workflow of ecs-deploy"
inputs:
  APP_ID:
    description: github app id
    required:    true
  PRIVATE_KEY:
    description: github private key
    required:    true
  REPOSITORY:
    description: ecr repository name
    required:    true
  TAG:
    description: ecr tag
    required:    true

runs:
  using: composite
  steps:
    - name:  Generate GitHub Apps token
      id:    generate_token
      shell: bash
      env:
        APP_ID:      ${{ inputs.APP_ID }}
        PRIVATE_KEY: ${{ inputs.PRIVATE_KEY }}
      run: |
        bash ${{ github.action_path }}/../generate-token.sh

    - name:  Workflow Dispatch
      shell: bash
      run:   |
        curl -s -X POST \
        -H "Authorization: token ${{ steps.generate_token.outputs.token }}" \
        -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/repos/taroshun32/taroshun32-actions/dispatches" \
        -d '{"event_type":"ecs-deploy","client_payload":{"REPOSITORY":"${{ inputs.REPOSITORY }}","TAG":"${{ inputs.TAG }}","FROM_CODE":"direct"}'

    - name:  Revoke GitHub Apps token
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.generate.outputs.token }}
      run: |        
        curl -s -X DELETE \
        -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
        -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/installation/token" \
