name: "deploy to ecs"

on:
  repository_dispatch:
    types:
      - deploy

jobs:
  deploy-ecs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy
        uses: ./github/actions/deploy
        with:
          ECR_IMAGE:      ${{ github.event.client_payload.ECR_IMAGE }}
          TASK_NAME:      ${{ github.event.client_payload.TASK_NAME }}
          CONTAINER_NAME: ${{ github.event.client_payload.CONTAINER_NAME }}
          CLUSTER_NAME:   ${{ github.event.client_payload.CLUSTER_NAME }}
          SERVICE_NAME:   ${{ github.event.client_payload.SERVICE_NAME }}
