name: "ecs-deploy"

on:
  repository_dispatch:
    types:
      - ecs-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ap-northeast-1

      - name: Dynamodb scan
        id:   dynamodb-scan
        uses: ./.github/actions/dynamodb-scan
        with:
          REPOSITORY: ${{ github.event.client_payload.REPOSITORY }}

      - name:  Download Amazon ECS task definition
        shell: bash
        run:   |
          aws ecs describe-task-definition --task-definition ${{ env.TASK }} --query taskDefinition > task-definition.json

      - name: Render Amazon ECS task definition
        id:   render-web-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name:  ${{ env.CONTAINER }}
          image:           "${{ env.ACCOUNT }}.dkr.ecr.ap-northeast-1.amazonaws.com/${{ env.REPOSITORY }}:${{ github.event.client_payload.TAG }}"

      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster:         ${{ env.CLUSTER }}
          service:         ${{ env.SERVICE }}
          task-definition: ${{ steps.render-web-container.outputs.task-definition }}
