name: "Slack"

on:
  workflow_dispatch:

jobs:
  slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: post message
        uses: ./.github/actions/slack
