name: "slack-notice"

on:
  repository_dispatch:
    types:
      - slack-notice

jobs:
  slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ap-northeast-1

      - name: Dynamodb scan
        uses: ./.github/actions/dynamodb-scan
        with:
          REPOSITORY: ${{ github.event.client_payload.REPOSITORY }}

      - name: Slack post
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "attachments": [
                {
                  "text": "イメージがアップされました。",
                  "fields": [
                    {
                      "short": true,
                      "value": "${{ env.REPOSITORY }}",
                      "title": "Repository"
                    },
                    {
                      "short": true,
                      "value": "${{ github.event.client_payload.TAG }}",
                      "title": "Tag"
                    },
                    {
                      "short": true,
                      "value": "${{ env.SERVICE }}",
                      "title": "Service"
                    },
                    {
                      "short": true,
                      "value": "${{ env.CLUSTER }}",
                      "title": "Container"
                    }
                  ]
                },
                {
                  "callback_id": "confirm",
                  "text": "デプロイしますか？",
                  "actions": [
                    {
                      "text": "デプロイする",
                      "type": "button",
                      "name": "deploy",
                      "value": "${{ env.REPOSITORY }}:${{ github.event.client_payload.TAG }}"
                    },
                    {
                      "text": "デプロイしない",
                      "type": "button",
                      "name": "not_deploy",
                      "value": "not_deploy"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
