name: "test"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Post confirm button 2
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "attachments": [
                {
                  "text": "rollback する場合は以下から image を選択してください。",
                  "attachment_type": "default",
                  "callback_id": "rollback",
                  "actions": [
                    {
                      "name": "rollback",
                      "text": "select image",
                      "type": "select",
                      "options": [
                        {
                          "text": "svelte-app:1.0.0",
                          "value": "svelte-app:1.0.0",
                          "confirm": {
                            "title": "最終確認",
                            "text": "本当にデプロイしますか？",
                            "ok_text": "はい",
                            "dismiss_text": "いいえ"
                          }
                        },
                        {
                          "text": "Bridge",
                          "value": "bridge",
                          "confirm": {
                            "title": "最終確認",
                            "text": "本当にデプロイしますか？",
                            "ok_text": "はい",
                            "dismiss_text": "いいえ"
                          }
                        },
                        {
                          "text": "Checkers",
                          "value": "checkers",
                          "confirm": {
                            "title": "最終確認",
                            "text": "本当にデプロイしますか？",
                            "ok_text": "はい",
                            "dismiss_text": "いいえ"
                          }
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
